NavClub: Club
NavCompanies: Companies
NavCourses: Courses
NavWeeklyCompetitions: Weekly competitions
NavForum: Forum
NavArchive: Archive
NavContact: Contact
NavAdmin: Admin panel
AddPost: Add post
EditPosts: Edit posts
AddEvent: Add event
EditEvents: Edit events
AdminPanel: Admin panel
Post: Post
Posts: Posts
Remove: Remove
Cancel: Cancel
Save: Save
Edit: Edit
Back: Back
Title: Title
FormMissing: Error: Form missing
FormFailure err@Text: Error: #{err}
PostAdded: Post added
NotAdmin: You are not an admin
NotSuperAdmin:  You are not a super admin
AddUser: Add user
Admin: Admin
SuperAdmin: Super admin
Password: Password
Name: Name
Email: Email
UserAdded: User added
Logout: Logout
Login: Login
Users: Users
User: User
UserUpdated: User updated
NotImage: File you were trying to upload is not an image
ImageUploadFailed: Uploading the image failed
Edited: Edited
Events: Events
Event: Event
Organizer: Organizer
StartDate: Start date
EndDate: End date
EndDateInvalid: End date must be later than start date
EventAdded: Event added
EventEdited: Event edited
Update: Update
EditEvent: Edit event
Modified: modified
Companies: Companies
ZipCode: ZIP code
City: City
Phone: Phone
Sex: Sex
DateOfBirth: Date of birth
Membership: Membership
Send: Send
Magazine: Magazine
Check: Check
MembershipDisc: Membership disc
Address: Address
PDGANumber: PDGA Number
FirstName: First name
LastName: Last name
CheckError: Check error
LicenseAdultA: A-license, adult 55€
LicenseAdultB: B-license, adult 20€
LicenseJuniorA: A-license, junior 30€
LicenseJuniorB: B-license, junior 10€
Adult: Adult
Junior: Junior
Male: Male
Female: Female
MembershipDiscLabel: PDGA membership disc (only new members) 10€
MagazineLabel: PDGA Discgolfer-magazine 30€