NavClub: Club
NavCompanies: Companies
NavCourses: Courses
NavWeeklyCompetitions: Weekly competitions
NavForum: Forum
NavArchive: Archive
NavContact: Contact
NavAdmin: Admin panel
AddPost: Add post
EditPosts: Edit posts
AddEvent: Add event
EditEvents: Edit events
AdminPanel: Admin panel
Post: Post
Posts: Posts
Remove: Remove
Cancel: Cancel
Save: Save
Edit: Edit
Back: Back
Title: Title
FormMissing: Error: Form missing
FormFailure err@Text: Error: #{err}
PostAdded: Post added
NotAdmin: You are not an admin
NotSuperAdmin:  You are not a super admin
AddUser: Add user
Admin: Admin
SuperAdmin: Super admin
Password: Password
Name: Name
Email: Email
UserAdded: User added
Logout: Logout
Login: Login
Users: Users
User: User
UserUpdated: User updated
NotImage: File you were trying to upload is not an image
ImageUploadFailed: Uploading the image failed
Edited: Edited
Events: Events