NavClub: Seura
NavCompanies: Yrityksille
NavCourses: Radat
NavWeeklyCompetitions: Viikkokisat
NavForum: Foorumi
NavArchive: Arkisto
NavContact: Yhteystiedot
NavAdmin: Hallinta
AddPost: Lisää uutinen
EditPosts: Muokkaa uutisia
AddEvent: Lisää tapahtuma
EditEvents: Muokkaa tapahtumia
AdminPanel: Hallinta
Post: Uutinen
Posts: Uutiset
Remove: Poista
Cancel: Peruuta
Save: Tallenna
Edit: Muokkaa
Back: Takaisin
Title: Otsikko
FormMissing: Virhe: Lomake puuttuu
FormFailure err@Text: Virhe: #{err}
PostAdded: Uutinen lisätty
NotAdmin: Et ole ylläpitäjä
NotSuperAdmin:  Et ole pääylläpitäjä
AddUser: Lisää käyttäjä
Admin: Ylläpitäjä
SuperAdmin: Pääylläpitäjä
Password: Salasana
Name: Nimi
Email: Sähköposti
UserAdded: Käyttäjä lisätty
Logout: Kirjaudu ulos
Login: Kirjaudu sisään
Users: Käyttäjät
User: Käyttäjä
UserUpdated: Käyttäjän tiedot päivitetty
NotImage: Tiedosto ei ole kuva
ImageUploadFailed: Kuvan lisäys epäonnistui
Edited: Muokattu
Events: Tapahtumat
Event: Tapahtuma
Organizer: Järjestäjä
StartDate: Alkupäivämäärä
EndDate: Loppupäivämäärä
EndDateInvalid: Loppupäivämäärä pitää olla myöhemmin kuin alkupäivämäärä
EventAdded: Tapahtuma lisätty
EventEdited: Tapahtuma muokattu
Update: Päivitä
EditEvent: Muokkaa tapahtumaa
Modified: muokattu
Companies: Yrityksille
ZipCode: Postinumero
City: Paikkakunta
Phone: Puhelinnumero
Sex: Sukupuoli
DateOfBirth: Syntymäaika
Membership: Jäsenmaksu
Send: Lähetä
Magazine: Lehti
Check: Tarkistus
MembershipDisc: Jäsenkiekko
Address: Osoite
PDGANumber: PDGA numero
FirstName: Etunimi
LastName: Sukunimi
CheckError: Tarkistusvirhe
LicenseAdultA: A-lisenssi, aikuinen 55€
LicenseAdultB: B-lisenssi, aikuinen 20€
LicenseJuniorA: A-lisenssi, juniori 30€
LicenseJuniorB: B-lisenssi, juniori 10€
Adult: Aikuinen
Junior: Juniori
Male: Mies
Female: Nainen
MembershipDiscLabel: PDGA-jäsenkiekko (vain uudet jäsenet) 10€
MagazineLabel:  PDGA Discgolfer-lehti 30€
ClubMembers: Jäsenet
NegativePDGANumber: PDGA numero ei voi olla negatiivinen
MemberAdded: Jäsen lisätty
Add: Lisää
EditPost: Muokkaa uutista
PostEdited: Uutinen muokattu
MondayShort: ma
TuesdayShort: ti
WednesdayShort: ke
ThursdayShort: to
FridayShort: pe
SaturdayShort: la
SundayShort: su
