NavClub: Seura
NavCompanies: Yrityksille
NavCourses: Radat
NavWeeklyCompetitions: Viikkokisat
NavForum: Foorumi
NavArchive: Arkisto
NavContact: Yhteystiedot
NavAdmin: Hallinta
AddPost: Lisää uutinen
EditPosts: Muokkaa uutisia
AddEvent: Lisää tapahtuma
EditEvents: Muokkaa tapahtumia
AdminPanel: Hallinta
Post: Uutinen
Posts: Uutiset
Remove: Poista
Cancel: Peruuta
Save: Tallenna
Edit: Muokkaa
Back: Takaisin
Title: Otsikko
FormMissing: Virhe: Lomake puuttuu
FormFailure err@Text: Virhe: #{err}
PostAdded: Uutinen lisätty
NotAdmin: Et ole ylläpitäjä
NotSuperAdmin:  Et ole pääylläpitäjä
AddUser: Lisää käyttäjä
Admin: Ylläpitäjä
SuperAdmin: Pääylläpitäjä
Password: Salasana
Name: Nimi
Email: Sähköposti
UserAdded: Käyttäjä lisätty
Logout: Kirjaudu ulos
Login: Kirjaudu sisään
Users: Käyttäjät
User: Käyttäjä
UserUpdated: Käyttäjän tiedot päivitetty
NotImage: Tiedosto ei ole kuva
ImageUploadFailed: Kuvan lisäys epäonnistui
Edited: Muokattu
Events: Tapahtumat
